<?php
include_once "../common/DB_switch.php";
?>
<?php       //前画面から受け取った内容を保持　　※次画面へ引き継ぎたい場合はsession等に値を入れなおす
if(isset($_POST['disp'])==true){
    if(isset($_POST['staffcode'])==false){
        header('Location:staff_ng.php');
        exit();
    }
    $staff_code=$_POST['staffcode'];
    header('Location:staff_disp.php?staffcode='.$staff_code);
    exit();
}
if(isset($_POST['add'])==true){
    header('Location:staff_add.php');
    exit();
}
if(isset($_POST['edit'])==true){
    if(isset($_POST['staffcode'])==false){
        header('Location:staff_ng.php');
        exit();
    }
    $staff_code=$_POST['staffcode'];
    header('Location:staff_edit.php?staffcode='.$staff_code);
    exit();
}
if(isset($_POST['delete'])==true){
    if(isset($_POST['staffcode'])==false){
        header('Location:staff_ng.php');
        exit();
    }
    $staff_code=$_POST['staffcode'];
    header('Location:staff_delete.php?staffcode='.$staff_code);
    exit();
}
?>